[package]
name = "shaku-rocket-test"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>"]
edition = "2018"

[dependencies]
shaku = { path = "../shaku/shaku" }
shaku_derive = { path = "../shaku/shaku_derive" }
rocket = "0.4.2"

[patch.crates-io]
shaku = { path = "../shaku/shaku" }
shaku_internals = { path = "../shaku/shaku_internals" }
shaku_derive = { path = "../shaku/shaku_derive" }
